services:
  - type: web
    name: khirad
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: bash build.sh
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://podshoevbunyod16-sketch.github.io
